@@ .. @@
 import React, { useState, useEffect } from "react";
 import { Link } from "react-router-dom";
-import { createPageUrl } from "@/utils";
-import { User } from "@/entities/User";
-import { UserHabit } from "@/entities/UserHabit";
-import { Habit } from "@/entities/Habit";
-import { HabitLog } from "@/entities/HabitLog";
-import { HabitStack } from "@/entities/HabitStack";
-import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
-import { Badge } from "@/components/ui/badge";
+import { createPageUrl } from "../utils";
+import { User } from "../entities/User";
+import { UserHabit } from "../entities/UserHabit";
+import { Habit } from "../entities/Habit";
+import { HabitLog } from "../entities/HabitLog";
+import { HabitStack } from "../entities/HabitStack";
+import { Button } from "../components/ui/button";
+import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
+import { Badge } from "../components/ui/badge";
